- platform: template
  sensors:
    cold_water_usage_changed:
      friendly_name: Cold Water Usage Changed
      value_template: >-
        {{ state_attr('sensor.cold_water_usage_mean', 'change') | float > 0.01 }}
    hot_water_usage_changed:
      friendly_name: Hot Water Usage Changed
      value_template: >-
        {{ state_attr('sensor.hot_water_usage_mean', 'change') | float > 0.01 }}
    motion_hb:
      friendly_name: Motion HB
      value_template: >-
          {{ is_state('binary_sensor.motion_sensor_158d0002b482e9', 'on')
             or is_state('binary_sensor.motion_sensor_158d0001e05856', 'on') }}
    sasha:
      friendly_name: Sasha tracker
      value_template: >-
        {{ is_state('input_boolean.sasha_tracker', 'on') }}
      
#      "{% if is_state('input_boolean.sasha_tracker', 'on') %}home{% else %}not_home{% endif %}"